workflows:
  ios-vision-build:
    name: VisionClaw iPhone Build
    instance_type: mac_mini_m2
    environment:
      groups:
        - default
      vars:
        XCODE_PROJECT: "samples/CameraAccess/CameraAccess.xcodeproj"
        XCODE_SCHEME: "CameraAccess"
    scripts:
      - name: Setup Secrets
        script: |
          cp samples/CameraAccess/CameraAccess/Secrets.swift.example samples/CameraAccess/CameraAccess/Secrets.swift
          sed -i '' "s/YOUR_GEMINI_API_KEY/$GEMINI_API_KEY/g" samples/CameraAccess/CameraAccess/Secrets.swift
      - name: Build App
        script: |
          xcodebuild build -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -configuration Release -sdk iphoneos CODE_SIGNING_ALLOWED=NO
      - name: Create IPA
        script: |
          mkdir -p Payload
          cp -r $(find . -name "*.app" | head -1) Payload/
          zip -r VisionClaw.ipa Payload
    artifacts:
      - "*.ipa"
